### ISSUE TITLE
问个研究方向的问题

### ISSUE THREAD

**Issue by nistarlwc** [M-3LAB/awesome-industrial-anomaly-detection#11]
为什么没有看到有人用遥感领域的变化检测change detection来做工业缺陷检测呢？
只要有个模板就可以用孪生网络把不同特征的位置检测出来。
是有什么限制了这种方法吗？
图像配准吗？现在也有深度学习的端到端配准了，就算配准偏差了几个像素，change detection应该也可以正常运行吧

**Comment by shirowalker** [comment]
> 为什么没有看到有人用遥感领域的变化检测change detection来做工业缺陷检测呢？ 只要有个模板就可以用孪生网络把不同特征的位置检测出来。 是有什么限制了这种方法吗？ 图像配准吗？现在也有深度学习的端到端配准了，就算配准偏差了几个像素，change detection应该也可以正常运行吧

主要问题还是在于工业品未必有固定的模板，现有数据集的同类物品往往有一定多样性。如果是有固定模板的工业品的话确实可以考虑用这种方法。刚好我们在NeurIPS 2023上的工作_Real3D-AD: A Dataset of Point Cloud Anomaly Detection_就是基于这一假设的，有兴趣的话欢迎关注。

**Comment by nistarlwc** [comment]
工业品应该都是有标准品的呀，只是可能会有旋转或者位移之类的变换，通过配准也能解决吧



---- 回复的原邮件 ----
| 发件人 | Jiaqi ***@***.***> |
| 日期 | 2024年02月21日 17:54 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [M-3LAB/awesome-industrial-anomaly-detection] 问个研究方向的问题 (Issue #11) |

为什么没有看到有人用遥感领域的变化检测change detection来做工业缺陷检测呢？ 只要有个模板就可以用孪生网络把不同特征的位置检测出来。 是有什么限制了这种方法吗？ 图像配准吗？现在也有深度学习的端到端配准了，就算配准偏差了几个像素，change detection应该也可以正常运行吧

主要问题还是在于工业品未必有固定的模板，现有数据集的同类物品往往有一定多样性。如果是有固定模板的工业品的话确实可以考虑用这种方法。刚好我们在NeurIPS 2023上的工作_Real3D-AD: A Dataset of Point Cloud Anomaly Detection_就是基于这一假设的，有兴趣的话欢迎关注。

**Comment by shirowalker** [comment]
> 工业品应该都是有标准品的呀，只是可能会有旋转或者位移之类的变换，通过配准也能解决吧
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | Jiaqi ***@***.***> | | 日期 | 2024年02月21日 17:54 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [M-3LAB/awesome-industrial-anomaly-detection] 问个研究方向的问题 (Issue #11) | 为什么没有看到有人用遥感领域的变化检测change detection来做工业缺陷检测呢？ 只要有个模板就可以用孪生网络把不同特征的位置检测出来。 是有什么限制了这种方法吗？ 图像配准吗？现在也有深度学习的端到端配准了，就算配准偏差了几个像素，change detection应该也可以正常运行吧 主要问题还是在于工业品未必有固定的模板，现有数据集的同类物品往往有一定多样性。如果是有固定模板的工业品的话确实可以考虑用这种方法。刚好我们在NeurIPS 2023上的工作_Real3D-AD: A Dataset of Point Cloud Anomaly Detection_就是基于这一假设的，有兴趣的话欢迎关注。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

理论上是这样的，但是现有的公开数据集不单包括标准工业品，比如最常见的MVTec AD数据集里的cable, wood等很多都没有固定模板。
