### ISSUE TITLE
Related work

### ISSUE THREAD

**Issue by wyzjack** [M-3LAB/awesome-industrial-anomaly-detection#12]
Hi authors,

Congrats on the nice and inspiring survey!
Could you include the survey paper [Explainable Anomaly Detection in Images and Videos: A
Survey](https://arxiv.org/pdf/2302.06670) ? Thanks in advance.

Best

**Comment by shirowalker** [comment]
> Hi authors,
> 
> Congrats on the nice and inspiring survey! Could you include the survey paper [Explainable Anomaly Detection in Images and Videos: A Survey](https://arxiv.org/pdf/2302.06670) ? Thanks in advance.
> 
> Best

Thanks for your sharing, we have added the paper in our repo.

**Comment by shirowalker** [comment]
> Hi authors,
> 
> Congrats on the nice and inspiring survey! Could you include the survey paper [Explainable Anomaly Detection in Images and Videos: A Survey](https://arxiv.org/pdf/2302.06670) ? Thanks in advance.
> 
> Best

Thanks for your sharing, we have added the paper in our repo.

**Comment by wyzjack** [comment]
Thanks!
