### ISSUE TITLE
Anomalib的文章链接好像错了

### ISSUE THREAD

**Issue by gaooolianggg** [M-3LAB/awesome-industrial-anomaly-detection#24]
在SOTA methods with code部分，Anomalib: A Deep Learning Library for Anomaly Detection的链接打开后是别的文章，[https://arxiv.org/abs/2307.12540](url)

**Comment by shirowalker** [comment]
> in the section , the paper <Anomalib: A Deep Learning Library for Anomaly Detection> may linked to a wrong paper,[https://arxiv.org/abs/2307.12540](url), it is <UniFormaly: Towards Task-Agnostic Unified Framework for Visual Anomaly Detection>

Thanks, we have fixed the error.
