### ISSUE TITLE
More AD paper in CVPR2023

### ISSUE THREAD

**Issue by EricLee0224** [M-3LAB/awesome-industrial-anomaly-detection#3]
1. SQUID: Deep Feature In-Painting for Unsupervised Anomaly Detection
2. Multimodal Industrial Anomaly Detection via Hybrid Fusion

**Comment by EricLee0224** [comment]
1. SQUID: Deep Feature In-Painting for Unsupervised Anomaly Detection
   ~~2. Multimodal Industrial Anomaly Detection via Hybrid Fusion~~

**Comment by shirowalker** [comment]
Previously, this paper was in our repository, but since it did not deal with the industrial AD dataset, we removed it. Thank you for your suggestion, we will add it back.
