### ISSUE TITLE
M3DM的代码

### ISSUE THREAD

**Issue by gaooolianggg** [M-3LAB/awesome-industrial-anomaly-detection#32]
本仓库中的3.4部分中的文章《Multimodal Industrial Anomaly Detection via Hybrid Fusion》未提供代码链接，但代码可以在https://github.com/TencentYoutuResearch/AnomalyDetection-M3DM找到。这个代码我并未进行验证，请你检查是否是正确的，是否可以添加到本仓库中

**Comment by gaooolianggg** [comment]
文章中的链接(https://github.com/nomewang/M3DM)也是有效的，貌似这个才是原作者的

**Comment by shirowalker** [comment]
> 本仓库中的3.4部分中的文章《Multimodal Industrial Anomaly Detection via Hybrid Fusion》未提供代码链接，但代码可以在[https://github.com/TencentYoutuResearch/AnomalyDetection-M3DM找到。这个代码我并未进行验证，请你检查是否是正确的，是否可以添加到本仓库中](https://github.com/TencentYoutuResearch/AnomalyDetection-M3DM%E6%89%BE%E5%88%B0%E3%80%82%E8%BF%99%E4%B8%AA%E4%BB%A3%E7%A0%81%E6%88%91%E5%B9%B6%E6%9C%AA%E8%BF%9B%E8%A1%8C%E9%AA%8C%E8%AF%81%EF%BC%8C%E8%AF%B7%E4%BD%A0%E6%A3%80%E6%9F%A5%E6%98%AF%E5%90%A6%E6%98%AF%E6%AD%A3%E7%A1%AE%E7%9A%84%EF%BC%8C%E6%98%AF%E5%90%A6%E5%8F%AF%E4%BB%A5%E6%B7%BB%E5%8A%A0%E5%88%B0%E6%9C%AC%E4%BB%93%E5%BA%93%E4%B8%AD)

感谢提醒，遗漏了3.4中M3DM的代码链接，不过在仓库其他两个部分可以找到M3DM的代码链接。youtu research发布的代码和原作者自己的版本相同，一样有效。
