### ISSUE TITLE
New paper

### ISSUE THREAD

**Issue by Ehteshamciitwah** [M-3LAB/awesome-industrial-anomaly-detection#37]
Paper:  Multi-scale feature reconstruction network for industrial anomaly detection
Code:  https://github.com/Ehteshamciitwah/MSFR

**Comment by shirowalker** [comment]
> Paper: Multi-scale feature reconstruction network for industrial anomaly detection Code: https://github.com/Ehteshamciitwah/MSFR

We have added the paper and code link in our repo.
