### ISSUE TITLE
Uneven results.

### ISSUE THREAD

**Issue by danielsoy** [M-3LAB/awesome-industrial-anomaly-detection#6]
Hi ppl!
Thanks for sharing your work!

I have an issue related to the results that I got by training this anomaly detection model:
[https://github.com/OpenAOI/anodet](url)

With my dataset:
[https://drive.google.com/drive/folders/1_OF6-_MNTskgPd5Sqqtm1-p4WqDu0Jhl?usp=sharing](url)

You can see in this video, that the model is giving a higher anomaly score to the samples
with anomalies located on the right side of the image frame:
[https://www.youtube.com/watch?v=W4-ZtpJtE5c&ab_channel=tektronix475](url)

What is your guess about the probable cause?

Thanks a lot!

**Comment by shirowalker** [comment]
Thanks for your contribution. We have added your code and data in our repository. By the way, there are some noises in youtube video.
